### ISSUE TITLE
[Bug]: Large space between moduels in edit menu

### ISSUE THREAD

**Issue by noahrider** [TreyRuffy/BetterF3#70] opened 2024-03-12 19:22 UTC
### Describe the Bug

In the Fabric 1.20.4 (i haven't been able to test the forge version yet) version of this mod, in the edit menu where you add and edit moduels, there is a lot of extra space in between the different moduels in the menu.

### Steps to Reproduce

How to see this for yourself:
Go the the edit menu
Edit the left or right moduels
There you go

### Expected Behavior

I saw in videos that there was not really any space between them, and in the 1.20.1 version of this mod that i used to use, it was fine.

### Screenshots

<img width="1367" alt="edit" src="https://github.com/TreyRuffy/BetterF3/assets/97214639/0f634c65-8f0a-4d6a-90ce-60ef21b4ec8d">

### Modloader Type

Fabric

### Modloader Version

1.20.4

### Mod Version

BetterF3 Fabric v9.0.0 (1.20.3/1.20.4)

**Comment by BenignPigeon** [comment] 2024-03-17 21:13
duplicate of #58 , do you have any other mods installed with it. It could be a mod conflict issue.

**Comment by TreyRuffy** [comment] 2024-03-18 05:34
Fixed in 9.0.1

**Closed as completed by TreyRuffy** 2024-03-18 05:34 UTC
