### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by verixyt3** [TreyRuffy/BetterF3#27] opened 2023-10-03 13:23 UTC
### Describe the Request

Hello, I'm asking you to make a version for _1.20.2 fabric or quilt on Modrinth_, **thank you very much!**

### Screenshots

![image](https://github.com/TreyRuffy/BetterF3/assets/138714269/3539e660-81b9-43e7-93ef-102c04ef8722)

### Modloader Type

Fabric

### Modloader Version

I always update the latest one

**Comment by Avakining** [comment] 2023-10-03 20:22
Duplicate of #25

**Closed as completed** 2023-11-13 00:03 UTC
