### ISSUE TITLE
[Bug]:  Shows nothing on 1.19.2

### ISSUE THREAD

**Issue by lockf** [TreyRuffy/BetterF3#23] opened 2023-08-22 20:20 UTC
### Describe the Bug

When the mod is installed and activated nothing shows when I press F3 besides the 3d Orientation pointer. (It's important to reference that It's not the only mod I have installed - 145 mods)

### Steps to Reproduce

- Install minecraft 1.19.2
- Install Forge
- copy mod
- Open
- Create world
- press "F3"

### Expected Behavior

I expected to show the details that come has preset

### Modloader Type

Minecraft Forge

### Modloader Version

43.2.21

### Mod Version

4.0.0

**Comment by WTFolsen** [comment] 2023-08-24 17:48
could you provide a modlist? Im having the same problem.

**Comment by lockf** [comment] 2023-08-24 17:50
I created one for me.

![Captura de ecrã 2023-08-24 025117](https://github.com/TreyRuffy/BetterF3/assets/72867366/fa18bbdb-ae07-4ba7-9b4f-c6e1f1f7d6f1)
![Captura de ecrã 2023-08-24 025132](https://github.com/TreyRuffy/BetterF3/assets/72867366/3c743716-e5da-4314-b53e-7baad6f9dee0)
![Captura de ecrã 2023-08-24 025201](https://github.com/TreyRuffy/BetterF3/assets/72867366/bc2067af-dec2-49ae-8181-f9feb03700f9)
![Captura de ecrã 2023-08-24 025223](https://github.com/TreyRuffy/BetterF3/assets/72867366/d2e99b8f-bd54-40f5-8644-c481a8362783)
![Captura de ecrã 2023-08-24 025246](https://github.com/TreyRuffy/BetterF3/assets/72867366/d9ce223c-b1f7-4e6b-818e-4cdab212379c)
![Captura de ecrã 2023-08-24 025304](https://github.com/TreyRuffy/BetterF3/assets/72867366/5fb11de3-ce1b-42ed-9dd3-025d0f5dae3c)
![Captura de ecrã 2023-08-24 025321](https://github.com/TreyRuffy/BetterF3/assets/72867366/98405142-955b-4c4a-9ebc-7ba93d1389f0)
![Captura de ecrã 2023-08-24 025343](https://github.com/TreyRuffy/BetterF3/assets/72867366/2376b6be-cd16-4bb0-a86f-007bd0b8f7c1)
![Captura de ecrã 2023-08-24 025400](https://github.com/TreyRuffy/BetterF3/assets/72867366/cf77aa20-334e-40a5-a92f-34d70a5cc499)
![Captura de ecrã 2023-08-24 025414](https://github.com/TreyRuffy/BetterF3/assets/72867366/00abac7f-d8a6-4b3a-8956-932549a1ef89)
![Captura de ecrã 2023-08-24 025431](https://github.com/TreyRuffy/BetterF3/assets/72867366/4a6338c9-0ed3-4a20-8895-db76033e5454)

**Comment by WTFolsen** [comment] 2023-08-24 18:35
from my testing it seems to be friends and foes which cuases the problem

**Comment by lockf** [comment] 2023-08-24 18:36
do you have the ic2 classic installed too?

> from my testing it seems to be friends and foes which cuases the problem

**Comment by WTFolsen** [comment] 2023-08-24 18:39
no

> do you have the ic2 classic installed too?

**Comment by lockf** [comment] 2023-08-24 18:41
i'm having trouble with it too and wanted to confirm if it was because of friends and foes

**Comment by WTFolsen** [comment] 2023-08-24 18:42
whats the problem with it?

**Comment by lockf** [comment] 2023-08-24 18:44
recipes don't show on JEI

**Comment by WTFolsen** [comment] 2023-08-24 18:50
none or some specific ones?

**Comment by lockf** [comment] 2023-08-24 18:52
i've started playing the new version about 2 days ago i havent advanced enough so, so far the ones associated to the macerator and extractor dont work

**Comment by WTFolsen** [comment] 2023-08-24 18:59
ive tested ic2 classic with jei and friends and foes and found no problem with the recipes. but maybe some of the jei addons messes it up?

**Comment by LimpLungs** [comment] 2023-09-26 05:21
I've found that with only 2 mods, Better F3 and The Aether in 1.19.2 it has the same issue, if that helps. The original issue, of the 3d orientation cursor being the only thing to show up.

**Comment by Nycto97** [comment] 2023-09-29 03:42
I only have this issue after trying to bring up the alt+F3 screen which normally shows the F3 with FPS and TPS graph.
So BetterF3 works, along with the 300+ mods I've installed, but doing alt+F3 is what gives me the same outcome as all of you get.

**Comment by syryna** [comment] 2023-10-12 14:23
i can confirm the Aether statement. I have at the moment 75 mods in my modpack but The Aether seems to be the one.

But can't tell if Aether Mod or BetterF3 is causing it.

Here is my results:
- all mods active including The Aether and BetterF3 -> pressing F3 hides map show the three axis for y,x,z but no BetterF3 data

- all mods active including The Aether but BetterF3 OFF -> old full F3 information working

- all mods active but The Aether OFF and BetterF3 ON -> BefferF3 showing full information

It seems they only do not work in combination.

**Comment by TreyRuffy** [comment] 2023-11-13 03:37
I believe this was fixed in update 4.0.1.

**Closed as completed by TreyRuffy** 2023-11-13 03:37 UTC
